<?php
    namespace App\Processors\Support;
    
	class Config {
		const YANDEX_API_KEY				= 'trnsl.1.1.20161025T070904Z.8cb3605edad92868.3d4ff2ffb943ee27eef5ebac97a4a39e1e7262e0';
		const DEBUG 						= true;
		const PARSING_ERROR_FIELD           = 'PARSING_ERROR';
		/* Fullname validate */
		const FULLNAME_INPUT_FIELD			= 'FULLNAME';

		const SURNAME_OUTPUT_FIELD 			= 'SURNAME';
		const FIRSTNAME_OUTPUT_FIELD 		= 'FIRSTNAME';
		const FATHERNAME_OUTPUT_FIELD 		= 'FATHERNAME';

		const GENDER_OUTPUT_FIELD			= 'GENDER';

		const SURNAME_VALID_OUTPUT_FIELD	= 'SURNAME_VALID';
		const FIRSTNAME_VALID_OUTPUT_FIELD	= 'FIRSTNAME_VALID';
		const FATHERNAME_VALID_OUTPUT_FIELD	= 'FATHERNAME_VALID';

		/* */

		/* Phone validate */
		const PHONE_INPUT_FIELD 			= 'PHONE';
		const WORK_PHONE_INPUT_FIELD		= 'WORK_PHONE';
		const MOBILE_PHONE_INPUT_FIELD		= 'MOBILE_PHONE';
		/* */

		/* E-mail validate */
		const EMAIL_INPUT_FIELD 			= 'EMAIL';
		const WORK_EMAIL_INPUT_FIELD		= 'WORK_EMAIL';
		const PRIVATE_EMAIL_INPUT_FIELD		= 'PRIVATE_EMAIL';
		/* */

		/* Card-holder validate */
//		const CARD_HOLDER_INPUT_FIELD					= 'FULLNAME';

//		const CARD_HOLDER_SURNAME_OUTPUT_FIELD 			= 'CARD_HOLDER_SURNAME';
//		const CARD_HOLDER_FIRSTNAME_OUTPUT_FIELD 		= 'CARD_HOLDER_FIRSTNAME';

//		const CARD_HOLDER_GENDER_OUTPUT_FIELD			= 'CARD_HOLDER_GENDER';

//		const CARD_HOLDER_SURNAME_VALID_OUTPUT_FIELD 	= 'CARD_HOLDER_SURNAME_VALID';
//		const CARD_HOLDER_FIRSTNAME_VALID_OUTPUT_FIELD 	= 'CARD_HOLDER_FIRSTNAME_VALID';
		/* */
	}